project:
  type: website
  output-dir: docs
  resources:
    - pdfs/**
    - notes/images/**

website:
  title: "Introduction to Bioinformatics"
  navbar:
    left: []
    right:
      - text: "Systems Biology"
        href: https://stefole.github.io/
      - text: "Molecular Biology"
        href: https://stefole.github.io/molbio/
      - text: "Course Specification"
        href: https://teaching.healthtech.dtu.dk/22111/index.php/22111:Course_plan_autumn_2025

format:
  html:
    theme:
      dark: darkly
      light: cosmo
    mainfont: "Inter"
    monofont: "Menlo"
    highlight-style:
      dark: dracula
      light: github
    code-copy: true
    code-overflow: wrap
    grid:
      body-width: 1100px
      gutter-width: 1rem
    css:
      - styles/fonts.css
      - styles/styles.css
